version: "3.7"

services:
  bitcoin-regtest:
    image:
      sovryn-bitcoind-regtest:latest

    build:
      context: ./integration_test/bitcoind-regtest/

    environment:
     # NOTE: these "secrets" are supposed to be there -- they are not used in the real world. Don't report them.
     - NODE1_HDSEED=cTj4tA23bVHAnA42bYGGPfv13G2dfuChxtenJKsZffkCVMvofcfC
     - NODE2_HDSEED=cUroJKmyKxRJVaeKzprMZExtPoZqt9HPnfhhJvAqtprWCVsuzUBU
     - NODE3_HDSEED=cSsv1YhxQqce8ywLiwhMjKcq9L1J7J2wm66zX7kfB1eLBBBaTt8N
     - USER_HDSEED=cUrw2SDAMapEqZ2pQnh5angJHqzGWvPMPdJNJWTDFagHMcdcciu8
     # sorted !!
     - PUBKEYS=["02f2bfc7a7d86f04d675083c7157d95c5741e85ff69b0c1357059fe1ee52271218","0380d87958cc14e1178f55584ee437b05c155a5a7d9f1951beb927195abaa7a7ed","0397ff0a671bea40a8346d7487810f3a96be95732717e5c568a7c8090a73a6c88b"]
     - MULTISIG_ADDRESS=bcrt1qtxysk2megp39dnpw9va32huk5fesrlvutl0zdpc29asar4hfkrlqs2kzv5
     # replenisher multisig

#rep1.txt:# extended private masterkey: tprv8ZgxMBicQKsPdn254GKf2bYkZkX7qYSTfp1Nd1cZ8mTVsd12ni2K9CmredbD7FY6UvJTfBXG3uJiF24hen5vycv1TUmS9g9MSGLbht9g8FK
#rep2.txt:# extended private masterkey: tprv8ZgxMBicQKsPevFzbHT9BG3m1m7ZtjniHW5UzECpbAPPMUdSisBVVBSJtZzJLWWJ4157NG9wrFqSKbsYBEhj5pWvBuncJANC2EuLi8oRawM

     - 'REPLENISHER_SOURCE_DESCRIPTOR=wsh(sortedmulti(2,tpubD6NzVbkrYhZ4XF3rwuzFS1Cs8n33zsdNF7c9uXerZ3Fti7FoR6quKhPipoXiSY8EXVhwvtCQjFxXMZJKoJNGyuXzaGVQJH6NpjXvo4jdMeQ/0/*,tpubD6NzVbkrYhZ4YPHnUw7jafhsandW44ycrogGGkF81SBnBxtDMG15fg4B4gzdNufXC6PjchXmfY4s2MsS77KDpBGJ8qRxvx4RUfqSzyqcHPq/0/*))#qjj6up2r'
     - REPLENISHER1_XPRV=tprv8ZgxMBicQKsPdn254GKf2bYkZkX7qYSTfp1Nd1cZ8mTVsd12ni2K9CmredbD7FY6UvJTfBXG3uJiF24hen5vycv1TUmS9g9MSGLbht9g8FK
     - REPLENISHER2_XPRV=tprv8ZgxMBicQKsPevFzbHT9BG3m1m7ZtjniHW5UzECpbAPPMUdSisBVVBSJtZzJLWWJ4157NG9wrFqSKbsYBEhj5pWvBuncJANC2EuLi8oRawM
     - REPLENISHER_ADDRESS=bcrt1qh0j5lcsvezdnrljsfcuetwrg7xen4a6ydmx9pt363e27rph2mntslwp447
     # Extra test vars
     - TEST_VERY_SMALL_REPLENISHER_COINS
     - TEST_REPLENISHER_LIMITS
     - TEST_SLOW_REPLENISHER

    ports:
      - 18443:18443

  hardhat:
    image:
      fastbtc-bidi-hardhat:latest

    build:
      context: ./packages/fastbtc-contracts/
      dockerfile: ../../integration_test/hardhat/Dockerfile

    environment:
     - NODE1_ADDRESS=0x4091663B0a7a14e35Ff1d6d9d0593cE15cE7710a
     - NODE2_ADDRESS=0x09dcD91DF9300a81a4b9C85FDd04345C3De58F48
     - NODE3_ADDRESS=0xA40013a058E70664367c515246F2560B82552ACb
     - USER_ADDRESS=0xB3b77A8Bc6b6fD93D591C0F34f202eC02e9af2e8

    ports:
      - 18545:8545

  node1:
    environment:
      - FASTBTC_RSK_RPC_URL=http://hardhat:8545
      - FASTBTC_BTC_RPC_URL=http://bitcoin-regtest:18443/wallet/multisig
      - FASTBTC_REPLENISHER_RPC_URL=http://bitcoin-regtest:18443/wallet/replenisher
      # Node1 is the only one that (potentially) sends alerts to discord in regtest
      - FASTBTC_ALERTER_DISCORD_WEBHOOK_URL
    depends_on:
      - bitcoin-regtest
      - hardhat

  node2:
    environment:
      - FASTBTC_RSK_RPC_URL=http://hardhat:8545
      - FASTBTC_BTC_RPC_URL=http://bitcoin-regtest:18443/wallet/multisig
      - FASTBTC_REPLENISHER_RPC_URL=http://bitcoin-regtest:18443/wallet/replenisher
    depends_on:
      - bitcoin-regtest
      - hardhat

  node3:
    image: fastbtc:latest
    env_file:
      - integration_test/nodes/docker-env3
      - integration_test/nodes/docker-env-common
    ports:
      - 11127:11127
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FASTBTC_RSK_RPC_URL=http://hardhat:8545
      - FASTBTC_BTC_RPC_URL=http://bitcoin-regtest:18443/wallet/multisig
      - FASTBTC_REPLENISHER_RPC_URL=http://bitcoin-regtest:18443/wallet/replenisher
    depends_on:
      - bitcoin-regtest
      - hardhat
      - pg
      - node1
      - node2
