CREATE USER fastbtc_node1 WITH ENCRYPTED PASSWORD 'node1';
CREATE USER fastbtc_node2 WITH ENCRYPTED PASSWORD 'node2';
CREATE USER fastbtc_node3 WITH ENCRYPTED PASSWORD 'node3';
CREATE DATABASE fastbtc1;
CREATE DATABASE fastbtc2;
CREATE DATABASE fastbtc3;
GRANT ALL PRIVILEGES ON DATABASE fastbtc1 to fastbtc_node1;
GRANT ALL PRIVILEGES ON DATABASE fastbtc2 to fastbtc_node2;
GRANT ALL PRIVILEGES ON DATABASE fastbtc3 to fastbtc_node3;
